services:
  - type: web
    name: your-backend-name
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
